baseurl = "http://0.0.0.0:8080/"
_baseurl = "http://santamariadeborreda.org/"
languageCode = "ca"
title = "Santa Maria de Borredà"
theme = "strata"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Albert Vilà Picas"
	description = "Història i presentació de monestirs per la seva conservació via micro-donacions"

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = ""

  [params.sidebar]
    bio = "**Santuari de la Popa**<p>@ Borredà, el Berguedà</p>"
    avatar = "vergeVitrall.png"
    background = "campanar.jpg"
		twitter = "albertvilapicas"
		github = "Creua"
    pinterest = "https://es.pinterest.com/santamariadeborreda/"
    teaming = "https://www.teaming.net/santamariadeborreda"
    teamingWidget = "https://www.teaming.net/group/spread/widgets/3kpO4w2C6LlfdxKlxYicx6G6ahdidPF7WBCF69p8hhVlf/"

		copyright = [
			"&copy; Bisbat de Vic"
		]

	[params.about]
		title = "Santa Maria de Borredà"
    header = "Santa Maria de Borredà fou des dels seus oígens església parroquial, dins de l'històric comtat de Berga; pertanyent al bisbat d’Urgell, fou possessió del monestir de Santa Maria de Ripoll."
    introduction = "El lloc i església de Borredà són esmentats per primera vegada l’any 886 en un plet entre el comte Guifré el Pelós i el bisbe Esclua; la resolució del plet fou favorable al comte i en ell es declarà que l’església i el lloc de Borredà peranyien a Guifré com hereu de Serrazino, llibert d'Ailone, tia del cornte, car els testirnonis varen declarar que trenta anys enrere l'esmentat Serrazino havia comprat aquesta església i havia troballat els erms de Borredà.\n\nCal pensar que fou el monestir de Ripoll l'encarregat de repoblar i organitzar el lloc de Borredà i fes seves sufragànies de Rotgers i de la Pera."
    teaming = ">_Teaming és una eina online per recaptar fons per causes socials a través de micro donacions d'1€ al mes. La filosofia de Teaming es basa en la idea de què sols, amb 1€, no podem fer massa però si ens unim, podem aconseguir fer realitat grans projectes._\n\n\nCal pensar també, que foren monjos de Ripoll els que van introduir a Borredà el culte a la mare de Déu, patrona del seu monestir. El comte Guifré devia cedir el lloc al monestir de Ripoll al final del segie (el seu fill, eI bisbe Radulf, arrodoní aquests dominis el segle X), però va retenir-ne per a ell i els seus successors la justícia del lloc, car l'any 1431 Alfons el Magnànim cedí la jurisdicció del lloc de Borredà als senyors de la Portella."
    sideContent = "L'any 901 Santa Maria de Borredà és esmentada com un dels límits de l’església de Sant Jaume de Frontanyà, en l’acta de consagració d'aquesta (_…et sic pervenit pro termino de Sta. Maria qui dicunt in Barresitano…_) l'any 912 el comte Miró, el vescomte Remesan i altres homes presidiren un judici on Longobard, mandatari de l'abat de Ripoll, exigia a uns homes de Borredà pagar a l'església de Santa Maria els delmes í primícies que eI bisbe Radulf havia donat al monestir de Rjpoll í que els particulars esmentats havien deixat de satisfer."
    context = "La propietat de Ripoll sobre Borredà quedà confirmada en la documentació d’aquest monestir del segle X; el precepte del Lluis del 938 confirma a Ripoll el lloc de Borredà, amb la seva parròquia i els seus súbdits; Lotari confirmava també aquest domini l’any 982 (_In pago Berguitano locum Brositano alodem sicut in illorum judicio ressonat, et parrochia sanctae Mariae cum ecclesiis sibi subditis…_). A precs del bisbe Oliba, el papa Sergi IV confirmava, en una butlla l'any 1011, els béns de Ripoll, entre els quals esmentat novament Borredà.\n\nLes notícies de l'església de Santa Marta de Borredà sovintegen al llarg del segle XI en la documentació del monestir de sant Pare de la Portella, car aquest monestir tenia possessions drets al terme del castell de Roset i santa Maria de Borredà, n'és un dels seus límits territorlaIs."
    historyTitle = "Santa Maria de Borredà"
    history = "L'església de Borredà fou sempre parroquial i en la visita al deganat de Berga pel visitador d'Urgell„ l'any 1312, es confirma aquesta autonomia. Com les esglésies del Berguedà que eren domini de Ripoll fou objecte, el segle XVI, d'un plet entre el recent creat bisbat de Solsona i el monestir de Ripoll. Fruit del concordat de l'any 1835 l'església de santa Maria de Borredà com parroquial, juntament amb les seves sufragagànies passà deflnitivament al bisbat de VIc, i conserva avui totes les seves funcions.\n\nEl temple primitiu de Santa Maria desaparegué quan al segle Xl fou aixecada una nova església romànica. Aquest segon temple és el que ens ha deixat algun vestigi que encara avui es pot veure. Ens referim al mur de ponent que deixa veure un tros d'aparell ben ordenat, a base de blocs de pedra petits, a manera de llambordes, disposats en filades uniformes i a trencajunt de mitja peça.\n\n"
    final = "La portalada que hi ha oberta a aquest mateix mur fou refeta el segle XVIII i ha perdut la seva faiçó original.\n\nHom pot veure també damunt la rosassa moderna feta damunt el portal, el pinyó o el doble cimal del vesant de la teulada primitiva.\n\n\n\nPossiblement hi hagi encara altres vestigis, però actualment es troben tapats i ofegats per la construcció moderna.\n\nL'església romànica fou ampliada primerament amb unes capelles laterals, de les quals encara en una, hi ha escrita la data del 1720. Entre els anys 1770 i 1780 l'edifici fou refet de manera substancial, de manera que el temple prengué forma de tres naus, amb un presbiteri rectangular, una capella fonda a l'esquerra i una sagristia a mà dreta. Hi ha noticies que l'any 1790 s'estava construint el campanar."
    quote = "_**Catalunya Romànica — volum XII Berguedà — pàgines 131,132.**_"

  [params.heading]
		[[params.heading.gallery]]
			image = "gallery/retaule.jpg"
			thumb = "gallery/retaule.jpg"
		[[params.heading.gallery]]
			image = "gallery/popa_v.jpg"
			thumb = "gallery/popa_t.jpg"
		[[params.heading.gallery]]
			image = "gallery/mausuleo.jpg"
			thumb = "gallery/mausuleo.jpg"

  [params.context]
		[[params.context.gallery]]
			image = "gallery/frontal.jpg"
			thumb = "gallery/frontal.jpg"
		[[params.context.gallery]]
			image = "gallery/totretaule.jpg"
			thumb = "gallery/totretaule.jpg"
		[[params.context.gallery]]
			image = "gallery/sanefa.jpg"
			thumb = "gallery/sanefa.jpg"

  [params.history]
		[[params.history.gallery]]
			image = "gallery/darrera.jpg"
			thumb = "gallery/darrera.jpg"
		[[params.history.gallery]]
			image = "gallery/roca.jpg"
			thumb = "gallery/roca.jpg"
		[[params.history.gallery]]
			image = "gallery/plasa.jpg"
			thumb = "gallery/plasa.jpg"

  [params._portfolio]
		title = "Galeria d'imatges"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params._portfolio.gallery]]
			image = "back.jpg"
			thumb = "back.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."
		[[params._portfolio.gallery]]
			image = "POPA.JPG"
			thumb = "POPA.JPG"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."
		[[params._portfolio.gallery]]
			image = "back.jpg"
			thumb = "back.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


	[params.contact]
		title = "Contacte"
		content = "Escriu-nos qualsevol suggerència per a millorar la informació.\nPer contactar amb l'Arxiprestat del Ripollès, podeu contactar amb `Mn. Melitó Tubau` al 972 70 02 43 i  <a href='parroquiesripoll@yahoo.es'>_parroquiesripoll@yahoo.es_</a>"

		address = [
			"Plaça Major",
			"08619 – Borredà",
			"Barcelona"
		]
		phone = "647 66 23 86 "

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "maquinaire@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Nom"
			email = "E-mail"
			message = "Missatge"
			submit = "Enviar missatge"
